export const initialGame = {
    'a8': 'black_Rook',
    'b8': 'black_Knight',
    'c8': 'black_Bishop',
    'd8': 'black_Queen',
    'e8': 'black_King',
    'f8': 'black_Bishop',
    'g8': 'black_Knight',
    'h8': 'black_Rook',
    'a7': 'black_pawn',
    'b7': 'black_pawn',
    'c7': 'black_pawn',
    'd7': 'black_pawn',
    'e7': 'black_pawn',
    'f7': 'black_pawn',
    'g7': 'black_pawn',
    'h7': 'black_pawn',
    
    'a1': 'white_Rook',
    'b1': 'white_Knight',
    'c1': 'white_Bishop',
    'd1': 'white_Queen',
    'e1': 'white_King',
    'f1': 'white_Bishop',
    'g1': 'white_Knight',
    'h1': 'white_Rook',
    'a2': 'white_pawn',
    'b2': 'white_pawn',
    'c2': 'white_pawn',
    'd2': 'white_pawn',
    'e2': 'white_pawn',
    'f2': 'white_pawn',
    'g2': 'white_pawn',
    'h2': 'white_pawn',
}
